server:
  port: 8086 # Specify the port on which the microservice will run

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doctordb
    username: root
    password: 0823


  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

